#!/bin/bash

WD=`pwd`

cd ../guncat 
    build man || exit 1
cd $WD

yodl2html index.yo || exit 1

scp ../guncat/tmp/manhtml/guncat.1.html index.html \
    fbb,guncat@web.sourceforge.net:htdocs/

echo -n "update the images as well [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    scp guncat.jpg fbb,guncat@web.sourceforge.net:htdocs/
fi

rm index.html

cd ../guncat 
    build distclean
